yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

yatube/about/models.py
# from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return f'Группа: {self.title}'


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='post_list'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups'
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-pub_date']

yatube/users/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    body = models.TextField()
    is_answered = models.BooleanField(default=False)

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = {
            'text',
            'group'
        }
        labels = {
            'text': 'Текст',
            'group': 'Группа'
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms
from .models import Contact

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'body')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'
# Описать класс AboutAuthorView для страницы about/author


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'
# Описать класс AboutTechView для страницы about/tech

yatube/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from .models import Group, User, Post
from .utils import pagntr

from .forms import PostForm


POSTS_AMOUNT = 10


def index(request):
    post_list = Post.objects.select_related('author', 'group')
    page_obj = pagntr(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.groups.select_related('group', 'author')
    page_obj = pagntr(request, post_list)
    context = {
        'page_obj': page_obj,
        'group': group,

    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    # Здесь код запроса к модели и создание словаря контекста
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.select_related('author').filter(
        author__username=username
    )
    page_obj = pagntr(request, post_list)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if not request.method == 'POST':
        context = {
            'form': form
        }
        return render(request, 'posts/create_post.html', context)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    is_edit = True
    form = PostForm(request.POST or None, instance=post)
    if request.method == 'POST':
        if not form.is_valid():
            context = {
                'form': form,
                'is_edit': is_edit,
                'post_id': post_id,
            }
            return render(request, 'posts/create_post.html', context)
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': is_edit,
        'post_id': post_id,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm, ContactForm
from .models import Contact


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


def user_contact(request):
    contact = Contact.objects.get(pk=3)
    form = ContactForm(instance=contact)
    return render(request, 'users/contact.html', {'form': form})

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}

{% block content %}
<h1>Автор: Полина Безруких</h1>
<p>
  Я бы вставила тут картинки, но очень спешу с проектом, так как еле поспеваю за спринтами.
  Потом я всегда смогу их дополнить, если надо будет.
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>И много что еще интересное</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    {% include 'includes/head.html' %}
    {% block title %}  
    {% endblock title %}
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock content %}
    </main>
    <footer>
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/head.html
    {% load static %}
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" src="{% static 'img/fav/favicon.ico' %}" type="image" >
    <link rel="apple-touch-icon" sizes="180x180" src="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" src="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" src="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

yatube/templates/includes/header.html
{% load static %}
<header>
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
      <li class="nav-item">              
        <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
           href="{% url 'about:author' %}"
        >
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
          href="{% url 'about:tech' %}"
        >
          Технологии
        </a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
          href="{% url 'posts:post_create' %}"
        >
          Новая запись
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
          href="{% url 'users:logout' %}"
        >
          Выйти
        </a>
      </li>
      <li>
        <a class="nav-link link-dark" > Пользователь: {{ user.username }}</a>
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'users:login' %}"
        >
          Войти
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'users:signup' %}"
        >
          Регистрация
        </a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>      
</header> 

yatube/templates/posts/create_post.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->
  {% block title %}  
    <title>
      {% if is_edit %}
        Редактировать запись
      {% else %}
        Добавить запись
      {% endif %}
    </title>
    {% endblock title %}
  
    {% block content %}     
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Добавить запись
                {% endif %}             
              </div>
              <div class="card-body">
                {% load user_filters %}
                {% include 'posts/includes/post_form.html' %}
                {% if is_edit %}        
                  <form method="post" action="{% url 'posts:post_edit' post_id %}">
                {% else %}
                  <form method="post" action="{% url 'posts:post_create' %}">
                {% endif%}
                  {% csrf_token %}
                  {{ form.as_p }}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->
  {% block title %} 
    <title>{{group}}</title>
  {% endblock title %}
  
  {% block content %}
    <div class="container py-5">
      <h1>{{group.title}}</h1>
      <p>{{group.description}}</p>
      {% for post in page_obj %}
        <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>
              {{ post.text|linebreaksbr }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">
              подробная информация
            </a>
        </article>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
      </div>  
    </main>
  {% endblock content %}

yatube/templates/posts/includes/paginator.html
{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}
 

yatube/templates/posts/includes/post_form.html
{% if form.errors %}
  {% for field in form %} 
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->
  {% block title %}  
    <title>Последние обновления на сайте</title>
  {% endblock title %}
  
  {% block content %}
      <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            <p>
              {{ post.text|linebreaksbr }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">
              подробная информация
            </a>
            <br>
          </article>
          {% if post.group %}      
            <a href= "{% url 'posts:group_list' post.group.slug %}"> все записи группы 
            </a>
          {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
          {% include 'posts/includes/paginator.html' %}
        </article>
        <!-- под последним постом нет линии -->
      </div>  
  {% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->
{% block title %}  
    <title>Пост {{ post.text|truncatechars:30 }}</title>
{% endblock title %}

{% block content %}
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            <li class="list-group-item">
              <!-- Название группы -->
              Группа: {{ post.group.title }}, {{ post.group.description|linebreaksbr }}
              {% if post.group %} <br> 
              <a href="{% url 'posts:group_list' post.group.slug %}">
                Все записи группы
              </a>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.post_list.count }}</span>
            </li>
            <li class="list-group-item">
              {% if post.author %}
                <a href="{% url 'posts:profile' post.author.username %}">
                  Все посты пользователя
                </a>
              {% endif %} 
            </li>
            {% if request.user.id == post.author.id %}
            <a class="d-flex justify-content-center" href="{% url 'posts:post_edit' post.id %}">
              <button class="btn btn-primary">
              Редактировать запись
              </button>
            </a>
            {% endif%}
      </aside>
      <article class="col-12 col-md-9">
        <p>
        {{ post.text|linebreaksbr }} 
        </p>
      </article>
    </div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->
  {% block title %}  
    <title>Профайл пользователя {{ author.get_full_name }}</title>
  {% endblock title %}
  
  {% block content %}
      <div class="container py-5">
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ author.post_list.count }} </h3>
        {% for post in page_obj %}  
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                Все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          <p>
            {{ post.text|linebreaksbr }} 
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a>
        </article>       
          {% if post.group %}      
            <a href= "{% url 'posts:group_list' post.group.slug %}"> Все записи группы 
            </a>
          {% endif %}        
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}  
      </div>
  {% endblock content %}

yatube/templates/posts/update_post.html
{% extends 'base.html' %}  <!-- Расширение базового шаблона -->
  {% block title %}  
    <title>Новая запись</title>
  {% endblock title %}
  
  {% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
  {% endblock content %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
<title>
  {% block title %}Зарегистрироваться{% endblock title%}
</title>
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 